'Package - config-eslint':
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nESLint Config\\n"

'Package - config-prettier':
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nPrettier Config\\n"

'Package - config-typescript':
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nTypescript Config\\n"
