name: prettier-config
org: aetherjs
install: true
packagePath: packages/prettier-config
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: aether-development/utilities
gitHostVariant: github
