name: ts-config
org: aetherjs
install: true
packagePath: packages/ts-config
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: aether-development/utilities
gitHostVariant: github
