name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'package.json'
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: aether-development/.github/actions/install-bun-dependencies@main
        with:
          bun-version: latest

      - name: Build Prettier
        run: bun run build

      - name: Run ESLint
        run: bun run lint

  build:
    name: Building
    uses: aether-development/.github/.github/workflows/reusable-build.yml@main
