name: Continuous Delivery

# Define permissions required for publishing to GitHub Packages
permissions:
  contents: read # To checkout the repository
  packages: write # To push packages to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      package:
        description: The package to deploy (optional, deploys all if omitted)
        required: false
        type: choice
        options:
          - eslint-config
          - prettier-config
          - ts-config
      prNumber:
        description: The number of the PR that is being deployed
        required: false
        type: string
      ref:
        description: The branch that is being deployed. Should be a branch on the given repository
        required: false
        default: main
        type: string
      repository:
        description: The {owner}/{repository} that is being deployed.
        required: false
        default: aether-development/utilities
        type: string
      registry:
        description: The registry to publish the 'next'/'pr-*' tag to
        required: false
        default: npm
        type: choice
        options:
          - npm
          - github
          - both
  push:
    branches:
      - main
    paths:
      # Trigger if either package changes, or the workflow itself changes
      - 'packages/eslint-config/**'
      - 'packages/prettier-config/**'
      - 'packages/ts-config/**'
      - '.github/workflows/continuous-delivery.yml'
      - '.github/workflows/reusable-continuous-delivery.yml'

jobs:
  determine-packages:
    name: Determine Packages to Publish
    runs-on: ubuntu-latest
    outputs:
      packages_json: ${{ steps.determine.outputs.packages_json }}
    steps:
      - name: Determine Packages using Composite Action
        id: determine
        uses: aether-development/.github/.github/actions/determine-packages@main
        with:
          event_name: ${{ github.event_name }}
          dispatch_package_input: ${{ github.event.inputs.package }}
          # Define the package configuration as a multi-line YAML string
          packages_config: |
            packages:
              eslint-config:
                paths:
                  - 'packages/eslint-config/**'
              prettier-config:
                paths:
                  - 'packages/prettier-config/**'
              ts-config:
                paths:
                  - 'packages/ts-config/**'
            common_paths:
              - '.github/workflows/continuous-delivery.yml'
              - '.github/workflows/reusable-continuous-delivery.yml'

  Publish:
    needs: determine-packages
    if: needs.determine-packages.outputs.packages_json != '[]'
    # Updated job name for clarity
    name: Publish Next/PR ${{ matrix.package }} to NPM & GitHub
    strategy:
      fail-fast: false
      matrix:
        # Dynamically generate matrix from the JSON output of determine-packages job
        package: ${{ fromJSON(needs.determine-packages.outputs.packages_json) }}

    uses: aether-development/.github/.github/workflows/reusable-continuous-delivery.yml@main
    with:
      build: true
      pr-number: ${{ github.event.inputs.prNumber }}
      ref: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.ref }}
      repository: ${{ github.event_name == 'push' && github.repository || github.event.inputs.repository }}
      working-directory: packages/${{ matrix.package }}
      registry: ${{ github.event.inputs.registry }}
      npm-scope: '@aetherjs'
      github-scope: '@aether-development'
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      GH_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
