name: Automatic Label Sync

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Define permissions required for syncing labels
permissions:
  contents: read # To checkout the repository
  issues: write # To read/write labels on issues
  pull-requests: write # To read/write labels on pull requests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  label_sync:
    uses: aether-development/.github/.github/workflows/reusable-labelsync.yml@main
