name: Automatic Label Sync

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    label_sync:
        uses: aether-development/.github/.github/workflows/reusable-labelsync.yml@main
