name: "PR Automation"
on:
  pull_request_target:
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically label PR
        uses: actions/labeler@9fd24f1f9d6ceb64ba34d181b329ee72f99978a0 # tag=v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

      - name: Automatically assign reviewers
        if: github.event.action == 'opened'
        uses: kentaro-m/auto-assign-action@v1.2.1
