name: Publish Dev
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */24 * * *"

jobs:
  npm:
    name: npm
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: "@aetherjs/eslint-config"
            folder: "eslint-config"
          - package: "@aetherjs/prettier-config"
            folder: "prettier-config"
          - package: "@aetherjs/ts-config"
            folder: "ts-config"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'aether-development'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Install NodeJS v16
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@1c73980b09e7aea7201f325a7aa3ad00beddcdda # tag=v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build Dependencies
        run: yarn build --cache-dir=".turbo"

      - name: Publish
        run: |
          yarn workspace ${{ matrix.package }} release --preid "next.$(date +%s)-$(git rev-parse --short HEAD)"
          yarn workspace ${{ matrix.package }} npm publish --tag next || true
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Deprecate Old Versions
        run: yarn npm-deprecate --name "*next*" --package "${{ matrix.package }}" --message "This version has been automatically deprecated. Please use a newer version." --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
